import React, { useState } from "react";
import PropertyOwnerLayout from "../../components/propertyowner/PropertyOwnerLayout";
import { getOwnerRuntimeSession, clearOwnerRuntimeSession } from "../../utils/propertyowner";
import { 
  QrCode, Search, Trash2, CheckCircle2, 
  AlertCircle, Calendar, Plus
} from "lucide-react";
import { apiFetch } from "../../services/api";

export default function VisitorPassesPage() {
  const owner = getOwnerRuntimeSession();
  if (!owner?.loginId && typeof window !== "undefined") { 
    window.location.href = "/propertyowner/ownerlogin"; 
    return null; 
  }

  const [search, setSearch] = useState("");
  const [passes, setPasses] = useState([]);
  const [loading, setLoading] = useState(true);

  React.useEffect(() => {
    fetchPasses();
  }, [owner.loginId]);

  const fetchPasses = async () => {
    try {
      setLoading(true);
      const data = await apiFetch(`/api/visitors/owner/${owner.loginId}?status=Pre-approved`);
      if (data.success && data.visitors) {
        setPasses(data.visitors.map(v => ({
           id: v._id,
           code: `PASS-${v._id.substring(v._id.length-4).toUpperCase()}`,
           visitor: `${v.name} (${v.purpose})`,
           tenant: v.hostName,
           room: v.hostRoom,
           validity: "Until " + new Date(v.createdAt).toLocaleDateString(),
           status: v.status === "Pre-approved" ? "Approved" : v.status
        })));
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleRevoke = async (id) => {
    try {
      const data = await apiFetch(`/api/visitors/${id}/status`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status: 'Cancelled' })
      });
      if (data.success) {
        setPasses(prev => prev.map(p => p.id === id ? { ...p, status: "Revoked" } : p));
      }
    } catch (err) {
      console.error(err);
    }
  };

  const filteredPasses = passes.filter(p => 
    p.visitor.toLowerCase().includes(search.toLowerCase()) ||
    p.tenant.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <PropertyOwnerLayout 
      owner={owner} 
      title="Access Passes" 
      onLogout={() => { clearOwnerRuntimeSession(); window.location.href = "/propertyowner/ownerlogin"; }}
    >
      <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4 mb-8">
        <div>
          <h1 className="font-serif text-[38px] md:text-[44px] leading-[1.05] text-foreground">Visitor Passes</h1>
          <p className="mt-1.5 text-[13.5px] text-muted-foreground">Monitor pre-authorized QR gate passes generated by residents for parent visits or friends.</p>
        </div>
      </div>

      {/* Toolbar */}
      <div className="flex flex-col sm:flex-row gap-3 mb-6">
        <div className="relative flex-1">
          <Search className="size-4 absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
          <input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search visitor passes by guest name or resident..."
            className="w-full h-10 pl-9 pr-3 rounded-xl bg-card border border-border text-[13px] focus:outline-none focus:ring-2 focus:ring-primary/20 placeholder:text-muted-foreground"
          />
        </div>
      </div>

      {/* Grid of Passes */}
      {loading ? (
        <div className="py-12 text-center text-slate-500">Loading pre-authorized passes...</div>
      ) : filteredPasses.length === 0 ? (
        <div className="py-12 text-center text-slate-500">No active visitor passes found.</div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredPasses.map((p) => (
          <div key={p.id} className="rounded-2xl border border-border bg-card p-6 shadow-soft hover:shadow-md transition-all flex flex-col justify-between">
            <div className="space-y-4">
              <div className="flex justify-between items-start">
                <div className="size-10 rounded-xl bg-blue-500/10 text-blue-600 flex items-center justify-center">
                  <QrCode size={20} />
                </div>
                <span className={`text-[10px] uppercase font-bold tracking-wider px-2.5 py-0.5 rounded-full border ${
                  p.status === "Approved" 
                    ? "bg-emerald-50 text-emerald-600 border-emerald-100" 
                    : "bg-rose-50 text-rose-600 border-rose-100"
                }`}>
                  {p.status}
                </span>
              </div>

              <div>
                <span className="text-[11px] font-mono font-bold text-slate-400 block mb-1">{p.code}</span>
                <h3 className="font-serif text-[21px] font-bold text-foreground">{p.visitor}</h3>
                <p className="text-[12.5px] text-muted-foreground mt-0.5">Invited by: <strong className="text-foreground">{p.tenant} (Room {p.room})</strong></p>
              </div>

              <div className="border-t border-border/60 pt-4 flex justify-between items-center text-xs text-muted-foreground">
                <span>Validity Period:</span>
                <span className="font-bold text-slate-800">{p.validity}</span>
              </div>
            </div>

            {p.status === "Approved" && (
              <div className="border-t border-border/60 mt-6 pt-4 flex gap-2">
                <button 
                  onClick={() => handleRevoke(p.id)}
                  className="flex-1 h-10 border border-rose-200 hover:bg-rose-50 text-rose-600 rounded-xl text-xs font-bold transition-all"
                >
                  Revoke Access Pass
                </button>
              </div>
            )}
          </div>
        ))}
        </div>
      )}
    </PropertyOwnerLayout>
  );
}
