import React, { lazy } from "react";

const pageModules = import.meta.glob("./pages/**/*.jsx");
const rootModules = import.meta.glob("./HomePage.jsx");
const frontendModules = import.meta.glob("../../Frontend/src/*.jsx");

// Merge all modules
const allModules = { ...pageModules, ...rootModules, ...frontendModules };

const routeEntries = [
  // Superadmin Routes
  ["/superadmin/areaadmin", "./pages/superadmin/areaadmin.jsx"],
  ["/superadmin/backup", "./pages/superadmin/backup.jsx"],
  ["/superadmin/booking", "./pages/superadmin/booking.jsx"],
  ["/superadmin/complaint-history", "./pages/superadmin/complaint-history.jsx"],
  ["/superadmin/complaints/tenants", "./pages/superadmin/TenantComplaints.jsx"],
  ["/superadmin/complaints/owners", "./pages/superadmin/OwnerComplaints.jsx"],
  ["/superadmin/direct-bookings", "./pages/superadmin/DirectBookings.jsx"],
  ["/superadmin/enquiry-approved", "./pages/superadmin/enquiry-approved.jsx"],
  ["/superadmin/enquiry-db", "./pages/superadmin/enquiry-db.jsx"],
  ["/superadmin/enquiry-hold", "./pages/superadmin/enquiry-hold.jsx"],
  ["/superadmin/enquiry-rejected", "./pages/superadmin/enquiry-rejected.jsx"],
  ["/superadmin/enquiry", "./pages/superadmin/enquiry.jsx"],
  ["/superadmin/import_local", "./pages/superadmin/import_local.jsx"],
  ["/superadmin/index", "./pages/superadmin/index.jsx"],
  ["/superadmin/kyc_verification", "./pages/superadmin/kyc_verification.jsx"],
  ["/superadmin/location", "./pages/superadmin/location.jsx"],
  ["/superadmin/log", "./pages/superadmin/log.jsx"],
  ["/superadmin/manager", "./pages/superadmin/manager.jsx"],
  ["/superadmin/monthly", "./pages/superadmin/monthly.jsx"],
  ["/superadmin/new_signups", "./pages/superadmin/new_signups.jsx"],
  ["/superadmin/notifications", "./pages/superadmin/AllNotifications.jsx"],
  ["/superadmin/owner", "./pages/superadmin/owner.jsx"],
  ["/superadmin/payment_disputes", "./pages/superadmin/payment_disputes.jsx"],
  ["/superadmin/platform", "./pages/superadmin/platform.jsx"],
  ["/superadmin/platform_reports", "./pages/superadmin/platform_reports.jsx"],
  ["/superadmin/profile", "./pages/superadmin/profile.jsx"],
  ["/superadmin/properties", "./pages/superadmin/properties.jsx"],
  ["/superadmin/total-properties", "./pages/superadmin/TotalProperties.jsx"],
  ["/superadmin/add-property", "./pages/superadmin/AddPropertyWizard.jsx"],
  ["/superadmin/amenities", "./pages/superadmin/AmenitiesManager.jsx"],
  ["/superadmin/pricing", "./pages/superadmin/PricingPlans.jsx"],
  ["/superadmin/featured", "./pages/superadmin/FeaturedListings.jsx"],
  ["/superadmin/property/pending", "./pages/superadmin/PendingProperties.jsx"],
  ["/superadmin/property/approvals", "./pages/superadmin/property_approvals.jsx"],
  ["/superadmin/employee-properties", "./pages/superadmin/employee_properties.jsx"],
  ["/superadmin/property/flagged", "./pages/superadmin/property_flagged.jsx"],
  ["/superadmin/property/categories", "./pages/superadmin/property_categories.jsx"],
  ["/superadmin/property/amenities", "./pages/superadmin/property_amenities.jsx"],
  ["/superadmin/property/pricing", "./pages/superadmin/property_pricing.jsx"],
  ["/superadmin/property/featured", "./pages/superadmin/property_featured.jsx"],
  ["/superadmin/property/moderation", "./pages/superadmin/property_moderation.jsx"],
  ["/superadmin/property/analytics", "./pages/superadmin/property_analytics.jsx"],
  ["/superadmin/property/settings", "./pages/superadmin/property_settings.jsx"],
  ["/superadmin/accounting", "./pages/superadmin/accounting_dashboard.jsx"],
  ["/superadmin/accounting/transactions", "./pages/superadmin/accounting_transactions.jsx"],
  ["/superadmin/accounting/commission", "./pages/superadmin/accounting_commission.jsx"],
  ["/superadmin/accounting/subscriptions", "./pages/superadmin/accounting_subscriptions.jsx"],
  ["/superadmin/accounting/payouts", "./pages/superadmin/accounting_payouts.jsx"],
  ["/superadmin/accounting/invoices", "./pages/superadmin/accounting_invoices.jsx"],
  ["/superadmin/accounting/taxes", "./pages/superadmin/accounting_taxes.jsx"],
  ["/superadmin/accounting/reports", "./pages/superadmin/accounting_reports.jsx"],
  ["/superadmin/accounting/settings", "./pages/superadmin/accounting_settings.jsx"],
  ["/superadmin/reports", "./pages/superadmin/reports_overview.jsx"],
  ["/superadmin/reports/listings", "./pages/superadmin/reports_listings.jsx"],
  ["/superadmin/reports/users", "./pages/superadmin/reports_users.jsx"],
  ["/superadmin/reports/leads", "./pages/superadmin/reports_leads.jsx"],
  ["/superadmin/reports/revenue", "./pages/superadmin/reports_revenue.jsx"],
  ["/superadmin/reports/commission", "./pages/superadmin/reports_commission.jsx"],
  ["/superadmin/reports/subscriptions", "./pages/superadmin/reports_subscriptions.jsx"],
  ["/superadmin/reports/refunds", "./pages/superadmin/reports_refunds.jsx"],
  ["/superadmin/reports/performance", "./pages/superadmin/reports_performance.jsx"],
  ["/superadmin/property/locations", "./pages/superadmin/property_locations.jsx"],
  ["/superadmin/reports/locations", "./pages/superadmin/property_locations.jsx"],
  ["/superadmin/reports/exports", "./pages/superadmin/reports_exports.jsx"],
  ["/superadmin/refund", "./pages/superadmin/refund.jsx"],
  ["/superadmin/rentcollection", "./pages/superadmin/rentcollection.jsx"],
  ["/superadmin/reviews", "./pages/superadmin/reviews.jsx"],
  ["/superadmin/reviews/all", "./pages/superadmin/AllReviews.jsx"],
  ["/superadmin/reviews/moderation", "./pages/superadmin/ReviewModeration.jsx"],
  ["/superadmin/reviews/analytics", "./pages/superadmin/ReviewAnalytics.jsx"],
  ["/superadmin/reviews/new", "./pages/superadmin/NewReviews.jsx"],
  ["/superadmin/security", "./pages/superadmin/security.jsx"],
  ["/superadmin/roles-permissions", "./pages/superadmin/RolesPermissions.jsx"],
  ["/superadmin/settings", "./pages/superadmin/settings.jsx"],
  ["/superadmin/superadmin", "./pages/superadmin/superadmin.jsx"],
  ["/superadmin/superchat", "./pages/superadmin/superchat.jsx"],
  ["/superadmin/tenant", "./pages/superadmin/tenant.jsx"],
  ["/superadmin/add-tenant", "./pages/superadmin/AddTenant.jsx"],
  ["/superadmin/visit", "./pages/superadmin/visit.jsx"],
  ["/superadmin/website-db", "./pages/superadmin/website-db.jsx"],
  ["/superadmin/website", "./pages/superadmin/website.jsx"],
  ["/superadmin/websiteenq", "./pages/superadmin/websiteenq.jsx"],
  ["/superadmin/user-overview", "./pages/superadmin/user-overview.jsx"],
  ["/superadmin/property-overview", "./pages/superadmin/property-overview.jsx"],
  ["/superadmin/accounting-overview", "./pages/superadmin/accounting-overview.jsx"],
  ["/superadmin/home-overview", "./pages/superadmin/home-overview.jsx"],
  
  // Employee Routes
  ["/employee/superadmin", "./pages/superadmin/superadmin.jsx"],
  ["/employee/areaadmin", "./pages/superadmin/superadmin.jsx"],
  ["/employee/backup", "./pages/superadmin/backup.jsx"],
  ["/employee/booking", "./pages/superadmin/booking.jsx"],
  ["/employee/complaint-history", "./pages/superadmin/complaint-history.jsx"],
  ["/employee/enquiry-approved", "./pages/superadmin/enquiry-approved.jsx"],
  ["/employee/enquiry-db", "./pages/superadmin/enquiry-db.jsx"],
  ["/employee/enquiry-hold", "./pages/superadmin/enquiry-hold.jsx"],
  ["/employee/enquiry-rejected", "./pages/superadmin/enquiry-rejected.jsx"],
  ["/employee/enquiry", "./pages/superadmin/enquiry.jsx"],
  ["/employee/import_local", "./pages/superadmin/import_local.jsx"],
  ["/employee/kyc_verification", "./pages/superadmin/kyc_verification.jsx"],
  ["/employee/location", "./pages/superadmin/location.jsx"],
  ["/employee/log", "./pages/superadmin/log.jsx"],
  ["/employee/manager", "./pages/superadmin/manager.jsx"],
  ["/employee/monthly", "./pages/superadmin/monthly.jsx"],
  ["/employee/new_signups", "./pages/superadmin/new_signups.jsx"],
  ["/employee/owner", "./pages/superadmin/owner.jsx"],
  ["/employee/payment_disputes", "./pages/superadmin/payment_disputes.jsx"],
  ["/employee/platform", "./pages/superadmin/platform.jsx"],
  ["/employee/platform_reports", "./pages/superadmin/platform_reports.jsx"],
  ["/employee/profile", "./pages/superadmin/profile.jsx"],
  ["/employee/properties", "./pages/superadmin/properties.jsx"],
  ["/employee/refund", "./pages/superadmin/refund.jsx"],
  ["/employee/rentcollection", "./pages/superadmin/rentcollection.jsx"],
  ["/employee/reviews", "./pages/superadmin/reviews.jsx"],
  ["/employee/security", "./pages/superadmin/security.jsx"],
  ["/employee/settings", "./pages/superadmin/settings.jsx"],
  ["/employee/superchat", "./pages/superadmin/superchat.jsx"],
  ["/employee/tenant", "./pages/superadmin/tenant.jsx"],
  ["/employee/visit", "./pages/employee/visit.jsx"],
  ["/employee/website-db", "./pages/superadmin/website-db.jsx"],
  ["/employee/website", "./pages/superadmin/website.jsx"],
  ["/employee/websiteenq", "./pages/superadmin/websiteenq.jsx"],
  
  // Property Owner Routes
  ["/propertyowner/admin", "./pages/propertyowner/admin.jsx"],
  ["/propertyowner/add-property", "./pages/propertyowner/AddPropertyWizard.jsx"],
  ["/propertyowner/booking-form", "./pages/propertyowner/booking-form.jsx"],
  ["/propertyowner/booking", "./pages/propertyowner/booking.jsx"],
  ["/propertyowner/booking_request", "./pages/propertyowner/booking_request.jsx"],
  ["/propertyowner/complaints", "./pages/propertyowner/complaints.jsx"],
  ["/propertyowner/documents", "./pages/propertyowner/documents.jsx"],
  ["/propertyowner/enquiry", "./pages/propertyowner/enquiry.jsx"],
  ["/propertyowner/index", "./pages/propertyowner/index.jsx"],
  ["/propertyowner/location", "./pages/propertyowner/location.jsx"],
  ["/propertyowner/ownerchat", "./pages/propertyowner/ownerchat.jsx"],
  ["/propertyowner/ownerlogin", "./pages/propertyowner/ownerlogin.jsx"],
  ["/propertyowner/ownerprofile", "./pages/propertyowner/ownerprofile.jsx"],
  ["/propertyowner/reports", "./pages/propertyowner/reports.jsx"],
  ["/propertyowner/payment-received", "./pages/propertyowner/payment-received.jsx"],
  ["/propertyowner/payment", "./pages/propertyowner/payment.jsx"],
  ["/propertyowner/properties", "./pages/propertyowner/properties.jsx"],
  ["/propertyowner/review", "./pages/propertyowner/review.jsx"],
  ["/propertyowner/rooms", "./pages/propertyowner/rooms.jsx"],
  ["/propertyowner/electricity-readings", "./pages/propertyowner/electricity-readings.jsx"],
  ["/propertyowner/schedulevisit", "./pages/propertyowner/schedulevisit.jsx"],
  ["/propertyowner/settings", "./pages/propertyowner/settings.jsx"],
  ["/propertyowner/tenantrec", "./pages/propertyowner/tenantrec.jsx"],
  ["/propertyowner/tenants", "./pages/propertyowner/tenants.jsx"],
  
  // New Demo Panels
  ["/staff/login", "./pages/staff-panel/login.jsx"],
  ["/staff", "./pages/staff-panel/dashboard.jsx"],
  ["/staff/tenants", "./pages/staff-panel/tenants.jsx"],
  ["/staff/rooms", "./pages/staff-panel/rooms.jsx"],
  ["/staff/complaints", "./pages/staff-panel/complaints.jsx"],
  ["/staff/tasks", "./pages/staff-panel/tasks.jsx"],
  ["/staff/visitors", "./pages/staff-panel/visitors.jsx"],
  ["/staff/attendance", "./pages/staff-panel/attendance.jsx"],
  ["/staff/electricity", "./pages/staff-panel/electricity.jsx"],

  ["/hostelowner", "./pages/owner-panel/dashboard.jsx"],
  ["/hostelowner/properties", "./pages/owner-panel/properties.jsx"],
  ["/hostelowner/staff", "./pages/owner-panel/staff.jsx"],
  ["/hostelowner/expenses", "./pages/owner-panel/expenses.jsx"],
  ["/hostelowner/rent", "./pages/owner-panel/rent.jsx"],
  ["/hostelowner/bookings", "./pages/owner-panel/bookings.jsx"],
  ["/hostelowner/complaints", "./pages/owner-panel/complaints.jsx"],
  ["/hostelowner/reviews", "./pages/owner-panel/reviews.jsx"],
  ["/hostelowner/reports", "./pages/owner-panel/reports.jsx"],
  
  // Tenant Routes
  ["/tenant/tenantagreement", "./pages/tenant/tenantagreement.jsx"],
  ["/tenant/tenantchat", "./pages/tenant/tenantchat.jsx"],
  ["/tenant/tenantcomplints", "./pages/tenant/tenantcomplints.jsx"],
  ["/tenant/tenantdashboard", "./pages/tenant/tenantdashboard.jsx"],
  ["/tenant/tenantlogin", "./pages/tenant/tenantlogin.jsx"],
  
  // Digital Checkin Routes
  ["/digital-checkin/index", "./pages/digital-checkin/index.jsx"],
  ["/digital-checkin/ownerkyc", "./pages/digital-checkin/ownerkyc.jsx"],
  ["/digital-checkin/ownerprofile", "./pages/digital-checkin/ownerprofile.jsx"],
  ["/digital-checkin/owner-success", "./pages/digital-checkin/owner-success.jsx"],
  ["/digital-checkin/ownerterms", "./pages/digital-checkin/ownerterms.jsx"],
  ["/digital-checkin/tenant-confirmation", "./pages/digital-checkin/tenant-confirmation.jsx"],
  ["/digital-checkin/tenantagreement", "./pages/digital-checkin/tenantagreement.jsx"],
  ["/digital-checkin/tenantkyc", "./pages/digital-checkin/tenantkyc.jsx"],
  ["/digital-checkin/tenantprofile", "./pages/digital-checkin/tenantprofile.jsx"],
  
    ["/propertyowner/occupancy-overview", "./pages/propertyowner/occupancy-overview.jsx"],
  ["/propertyowner/revenue-overview", "./pages/propertyowner/revenue-overview.jsx"],
  ["/propertyowner/quick-actions", "./pages/propertyowner/quick-actions.jsx"],
  ["/propertyowner/notifications", "./pages/propertyowner/notifications.jsx"],
  ["/propertyowner/activity-timeline", "./pages/propertyowner/activity-timeline.jsx"],
  ["/propertyowner/floors", "./pages/propertyowner/floors.jsx"],
  ["/propertyowner/beds", "./pages/propertyowner/beds.jsx"],
  ["/propertyowner/vacant-beds", "./pages/propertyowner/vacant-beds.jsx"],
  ["/propertyowner/amenities", "./pages/propertyowner/amenities.jsx"],
  ["/propertyowner/property-settings", "./pages/propertyowner/property-settings.jsx"],
  ["/propertyowner/active-tenants", "./pages/propertyowner/active-tenants.jsx"],
  ["/propertyowner/upcoming-moveins", "./pages/propertyowner/upcoming-moveins.jsx"],
  ["/propertyowner/moveout-requests", "./pages/propertyowner/moveout-requests.jsx"],
  ["/propertyowner/ex-tenants", "./pages/propertyowner/ex-tenants.jsx"],
  ["/propertyowner/kyc-verification", "./pages/propertyowner/kyc-verification.jsx"],
  ["/propertyowner/police-verification", "./pages/propertyowner/police-verification.jsx"],
  ["/propertyowner/tenant-ledger", "./pages/propertyowner/tenant-ledger.jsx"],
  ["/propertyowner/new-enquiries", "./pages/propertyowner/new-enquiries.jsx"],
  ["/propertyowner/follow-ups", "./pages/propertyowner/follow-ups.jsx"],
  ["/propertyowner/cancelled-bookings", "./pages/propertyowner/cancelled-bookings.jsx"],
  ["/propertyowner/lead-sources", "./pages/propertyowner/lead-sources.jsx"],
  ["/propertyowner/whatsapp-leads", "./pages/propertyowner/whatsapp-leads.jsx"],
  ["/propertyowner/security-deposits", "./pages/propertyowner/security-deposits.jsx"],
  ["/propertyowner/refunds", "./pages/propertyowner/refunds.jsx"],
  ["/propertyowner/discounts-offers", "./pages/propertyowner/discounts-offers.jsx"],
  ["/propertyowner/income", "./pages/propertyowner/income.jsx"],
  ["/propertyowner/vendor-payments", "./pages/propertyowner/vendor-payments.jsx"],
  ["/propertyowner/transactions", "./pages/propertyowner/transactions.jsx"],
  ["/propertyowner/profit-loss", "./pages/propertyowner/profit-loss.jsx"],
  ["/propertyowner/cash-flow", "./pages/propertyowner/cash-flow.jsx"],
  ["/propertyowner/reports", "./pages/propertyowner/reports.jsx"],
  ["/propertyowner/download-statements", "./pages/propertyowner/download-statements.jsx"],
  ["/propertyowner/open-tickets", "./pages/propertyowner/open-tickets.jsx"],
  ["/propertyowner/in-progress-complaints", "./pages/propertyowner/in-progress-complaints.jsx"],
  ["/propertyowner/resolved-complaints", "./pages/propertyowner/resolved-complaints.jsx"],
  ["/propertyowner/maintenance-requests", "./pages/propertyowner/maintenance-requests.jsx"],
  ["/propertyowner/assigned-staff", "./pages/propertyowner/assigned-staff.jsx"],
  ["/propertyowner/service-history", "./pages/propertyowner/service-history.jsx"],
  ["/propertyowner/maintenance-calendar", "./pages/propertyowner/maintenance-calendar.jsx"],
  ["/propertyowner/all-staff", "./pages/propertyowner/all-staff.jsx"],
  ["/propertyowner/add-staff", "./pages/propertyowner/add-staff.jsx"],
  ["/propertyowner/roles-permissions", "./pages/propertyowner/roles-permissions.jsx"],
  ["/propertyowner/staff-attendance", "./pages/propertyowner/staff-attendance.jsx"],
  ["/propertyowner/staff-tasks", "./pages/propertyowner/staff-tasks.jsx"],
  ["/propertyowner/staff-salaries", "./pages/propertyowner/staff-salaries.jsx"],
  ["/propertyowner/shift-management", "./pages/propertyowner/shift-management.jsx"],
  ["/propertyowner/staff-performance", "./pages/propertyowner/staff-performance.jsx"],
  ["/propertyowner/tenant-attendance", "./pages/propertyowner/tenant-attendance.jsx"],
  ["/propertyowner/visitor-entry", "./pages/propertyowner/visitor-entry.jsx"],
  ["/propertyowner/visitor-passes", "./pages/propertyowner/visitor-passes.jsx"],
  ["/propertyowner/entry-logs", "./pages/propertyowner/entry-logs.jsx"],
  ["/propertyowner/exit-logs", "./pages/propertyowner/exit-logs.jsx"],
  ["/propertyowner/leave-requests", "./pages/propertyowner/leave-requests.jsx"],
  ["/propertyowner/gate-management", "./pages/propertyowner/gate-management.jsx"],
  ["/propertyowner/daily-menu", "./pages/propertyowner/daily-menu.jsx"],
  ["/propertyowner/weekly-menu", "./pages/propertyowner/weekly-menu.jsx"],
  ["/propertyowner/meal-attendance", "./pages/propertyowner/meal-attendance.jsx"],
  ["/propertyowner/kitchen-inventory", "./pages/propertyowner/kitchen-inventory.jsx"],
  ["/propertyowner/grocery-expenses", "./pages/propertyowner/grocery-expenses.jsx"],
  ["/propertyowner/vendor-list", "./pages/propertyowner/vendor-list.jsx"],
  ["/propertyowner/food-feedback", "./pages/propertyowner/food-feedback.jsx"],
  ["/propertyowner/sms-campaigns", "./pages/propertyowner/sms-campaigns.jsx"],
  ["/propertyowner/email-notices", "./pages/propertyowner/email-notices.jsx"],
  ["/propertyowner/emergency-alerts", "./pages/propertyowner/emergency-alerts.jsx"],
  ["/propertyowner/communication-templates", "./pages/propertyowner/communication-templates.jsx"],
  ["/propertyowner/vacancy-promotion", "./pages/propertyowner/vacancy-promotion.jsx"],
  ["/propertyowner/social-media-leads", "./pages/propertyowner/social-media-leads.jsx"],
  ["/propertyowner/referral-program", "./pages/propertyowner/referral-program.jsx"],
  ["/propertyowner/property-website", "./pages/propertyowner/property-website.jsx"],
  ["/propertyowner/banners-posters", "./pages/propertyowner/banners-posters.jsx"],
  ["/propertyowner/coupons-offers", "./pages/propertyowner/coupons-offers.jsx"],
  ["/propertyowner/expense-reports", "./pages/propertyowner/expense-reports.jsx"],
  ["/propertyowner/tenant-analytics", "./pages/propertyowner/tenant-analytics.jsx"],
  ["/propertyowner/complaint-analytics", "./pages/propertyowner/complaint-analytics.jsx"],
  ["/propertyowner/staff-reports", "./pages/propertyowner/staff-reports.jsx"],
  ["/propertyowner/export-reports", "./pages/propertyowner/export-reports.jsx"],
  ["/propertyowner/staff-documents", "./pages/propertyowner/staff-documents.jsx"],
  ["/propertyowner/property-documents", "./pages/propertyowner/property-documents.jsx"],
  ["/propertyowner/uploaded-files", "./pages/propertyowner/uploaded-files.jsx"],
  ["/propertyowner/digital-signatures", "./pages/propertyowner/digital-signatures.jsx"],
  ["/propertyowner/current-plan", "./pages/propertyowner/current-plan.jsx"],
  ["/propertyowner/upgrade-plan", "./pages/propertyowner/upgrade-plan.jsx"],
  ["/propertyowner/billing-history", "./pages/propertyowner/billing-history.jsx"],
  ["/propertyowner/invoices", "./pages/propertyowner/invoices.jsx"],
  ["/propertyowner/payment-methods", "./pages/propertyowner/payment-methods.jsx"],
  ["/propertyowner/company-settings", "./pages/propertyowner/company-settings.jsx"],
  ["/propertyowner/property-settings-global", "./pages/propertyowner/property-settings-global.jsx"],
  ["/propertyowner/notification-settings", "./pages/propertyowner/notification-settings.jsx"],
  ["/propertyowner/payment-gateway", "./pages/propertyowner/payment-gateway.jsx"],
  ["/propertyowner/bank-accounts", "./pages/propertyowner/bank-accounts.jsx"],
  ["/propertyowner/integrations", "./pages/propertyowner/integrations.jsx"],
  ["/propertyowner/role-permissions", "./pages/propertyowner/role-permissions.jsx"],
  ["/propertyowner/language-settings", "./pages/propertyowner/language-settings.jsx"],
  ["/propertyowner/theme-settings", "./pages/propertyowner/theme-settings.jsx"],
  // Website Routes (using existing component names)
  ["/website/about", "./pages/website/AboutPage.jsx"],
  ["/website/contact", "./pages/website/ContactPage.jsx"],
  ["/website/cancellation", "./pages/website/WebsiteCancellation.jsx"],
  ["/website/terms", "./pages/website/WebsiteTerms.jsx"],
  ["/website/privacy", "./pages/website/WebsitePrivacy.jsx"],
  ["/website/refund", "./pages/website/WebsiteRefund.jsx"],
  ["/website/refund-request", "./pages/website/WebsiteRefundRequest.jsx"],
  ["/website/login", "./pages/website/WebsiteLogin.jsx"],
  ["/website/forgot-password", "./pages/website/WebsiteForgotPassword.jsx"],
  ["/website/signup", "./pages/website/WebsiteSignup.jsx"],
  ["/website/chat", "./pages/website/WebsiteChat.jsx"],
  ["/website/mystays", "./pages/website/WebsiteMystays.jsx"],
  ["/website/ourproperty", "./pages/website/OurPropertyPage.jsx"],
  ["/website/property-details/:propertyId", "./pages/website/PropertyDetailsPage.jsx"],
  ["/website/fast-bidding", "./pages/website/FastBiddingPage.jsx"],
  ["/website/pay", "./pages/website/PaymentCheckout.jsx"],
  ["/website/list", "./pages/website/ListYourPropertyPage.jsx"],
  ["/website/profile", "./pages/website/ProfilePage.jsx"],
  ["/website/settings", "./pages/website/SettingsPage.jsx"],
  ["/website/fav", "./pages/website/FavouritesPage.jsx"],
  ["/website/reviews", "./pages/website/ReviewsPage.jsx"],
  ["/website/faq", "./pages/website/FAQPage.jsx"],
  ["/website/index", "./HomePage.jsx"],
  ["/index", "./HomePage.jsx"],
  ["/coming-soon", "./pages/ComingSoon.jsx"],
  ["/", "./pages/ComingSoon.jsx"],
  ["/propertyowner/room-photos", "./pages/propertyowner/room-photos.jsx"],
  ["/propertyowner/tenant-docs", "./pages/propertyowner/tenant-docs.jsx"],
  ["/propertyowner/dues-report", "./pages/propertyowner/dues-report.jsx"],
  ["/propertyowner/late-fine", "./pages/propertyowner/late-fine.jsx"],
  ["/propertyowner/penalty-config", "./pages/propertyowner/penalty-config.jsx"],
  ["/propertyowner/payment-dashboard", "./pages/propertyowner/payment-dashboard.jsx"],
  ["/propertyowner/receipts", "./pages/propertyowner/receipts.jsx"],
  ["/propertyowner/collection-report", "./pages/propertyowner/collection-report.jsx"],
  ["/propertyowner/expense-tracking", "./pages/propertyowner/expense-tracking.jsx"],
  ["/propertyowner/revenue-analytics", "./pages/propertyowner/revenue-analytics.jsx"],
  ["/propertyowner/hra-gst", "./pages/propertyowner/hra-gst.jsx"],
  ["/propertyowner/agreement", "./pages/propertyowner/agreement.jsx"],
  ["/propertyowner/announcements", "./pages/propertyowner/announcements.jsx"],
  ["/propertyowner/whatsapp", "./pages/propertyowner/whatsapp.jsx"],
  ["/propertyowner/listing", "./pages/propertyowner/listing.jsx"],
  ["/propertyowner/occupancy-report", "./pages/propertyowner/occupancy-report.jsx"],
  ["/propertyowner/property-managers", "./pages/propertyowner/property-managers.jsx"],
  
  // Property Manager Routes
  ["/manager/login", "./pages/manager/login.jsx"],
  ["/manager/dashboard", "./pages/manager/dashboard.jsx"],
];

const buildRouteElement = (modulePath) => {
  const loader = allModules[modulePath];

  if (!loader) {
    throw new Error(`Missing route module: ${modulePath}`);
  }

  const Component = lazy(loader);
  return <Component />;
};

const processedEntries = [...routeEntries];
routeEntries.forEach(([path, modulePath]) => {
  if (path.startsWith("/superadmin/") && path !== "/superadmin/superadmin" && path !== "/superadmin/index") {
    const empPath = path.replace("/superadmin/", "/employee/");
    if (!processedEntries.find(r => r[0] === empPath)) {
      processedEntries.push([empPath, modulePath]);
    }
  }
});

const routes = processedEntries.map(([path, modulePath]) => ({
  path,
  element: buildRouteElement(modulePath)
}));

export default routes;
